[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "purecpp-oracledb"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["oracledb>=2.1"]

[tool.setuptools.packages.find]
where = ["."]
include = ["purecpp_oracledb*"]
